@DocHub.WebApi_HostAddress = http://localhost:7251

GET {{DocHub.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{DocHub.WebApi_HostAddress}}/api/documents
Accept: application/json